### ISSUE TITLE
Charlotte -- what do you think about dialog buttons overlapping bio text?

### ISSUE THREAD

**Issue by ttwerwer** [ttwerwer/Calera-Capital-finish-line#7]
As the text rises up, the dialog buttons float are sitting on top of it.  It's not a big deal.  We could have them change it so that the text disappears when it rises higher than the photo.

![00 scroll](https://cloud.githubusercontent.com/assets/24998172/22433565/a66f9396-e6cd-11e6-8959-44694426c623.png)

**Comment by calera-charlotte** [comment]
@ttwerwer I agree, I think that's a good solution.
